### ISSUE TITLE
Where is Octree?

### ISSUE THREAD

**Issue by jrodriguesimg** [pex-gl/pex-geom#18]
By looking at the [docs](https://vorg.github.io/pex/docs/pex-geom/Octree.html) I figured that this was the place to look for Octree but I can't find it . There are commits (ex: ca03f69c2809db0721267ae93f553c0422fcf1849) in this repo that refer to `lib/Octree.js` but there is no `lib/` folder. Was it removed?

**Comment by jrodriguesimg** [comment]
Oh. It was removed along with lots of code in re-init commit. Why?

**Comment by vorg** [comment]
Hi, Yes, octree was there in 0.x version where `pex-geom` was more a kitchen sink library. That has been streamlined in the recent versions. The newest docs are here https://github.com/pex-gl/pex-geom/blob/master/README.md

You can always install legacy version described in the docs you posted via pex-geom@0.11.0. Bear in mind the one of the biggest changes was moving from {x:1 ,y:2 ,z:3} vector objects to [1,2,3] vector arrays.



PS. How did you find the other docs? I don't remember linking them for a long time.
