### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [pex-gl/pex-geom#20]
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by vorg** [comment]
hi @geopic thank you for your offer. At this moment TS is not part of our workflow and this lib haven't got much love in the recent years so i woudn't like to waste too much of your time. Are you using `pex-geom` a lot? Could you share more?

**Comment by geopic** [comment]
It's no problem @vorg, I can spend time working on this. :smiley:  I don't use `pex-geom` personally but would like to contribute all the same if it's fine with you, unless you'd rather leave the library as it is since it's old. It'll just be a file and a `types` entry in `package.json`.

**Comment by vorg** [comment]
I think at this stage it's better to leave it where it is. Thank you.
